# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Capitalize
version:      0.7
version_from: Capitalize.pm
installdirs:  site
requires:
    Carp:                          1.01
    Env:                           1
    Exporter:                      5.562
    FindBin:                       1.04
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
